
package com.main.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-04-07T18:18:14.862-07:00
 * Generated source version: 3.3.0
 *
 */
public final class ShowTimeCreator_ShowTimeCreatorImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.main.com/", "ShowTimeCreatorImplService");

    private ShowTimeCreator_ShowTimeCreatorImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ShowTimeCreatorImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ShowTimeCreatorImplService ss = new ShowTimeCreatorImplService(wsdlURL, SERVICE_NAME);
        ShowTimeCreator port = ss.getShowTimeCreatorImplPort();

        {
        System.out.println("Invoking findShowtimeByMovieId...");
        int _findShowtimeByMovieId_arg0 = 0;
        try {
            java.util.List<com.main.ws.Showtime> _findShowtimeByMovieId__return = port.findShowtimeByMovieId(_findShowtimeByMovieId_arg0);
            System.out.println("findShowtimeByMovieId.result=" + _findShowtimeByMovieId__return);

        } catch (ShowtimeNotFound_Exception e) {
            System.out.println("Expected exception: ShowtimeNotFound has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking findShowtimeByShowtimeId...");
        int _findShowtimeByShowtimeId_arg0 = 0;
        try {
            com.main.ws.Showtime _findShowtimeByShowtimeId__return = port.findShowtimeByShowtimeId(_findShowtimeByShowtimeId_arg0);
            System.out.println("findShowtimeByShowtimeId.result=" + _findShowtimeByShowtimeId__return);

        } catch (ShowtimeNotFound_Exception e) {
            System.out.println("Expected exception: ShowtimeNotFound has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking createShowtime...");
        com.main.ws.Showtime _createShowtime_arg0 = new com.main.ws.Showtime();
        com.main.ws.Showtime _createShowtime__return = port.createShowtime(_createShowtime_arg0);
        System.out.println("createShowtime.result=" + _createShowtime__return);


        }

        System.exit(0);
    }

}
